"""empty message

Revision ID: 0a2e1602c752
Revises: 5b116927b345
Create Date: 2025-02-11 12:53:44.103117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2e1602c752'
down_revision: Union[str, None] = '5b116927b345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###