"""empty message

Revision ID: 14107f8df40b
Revises: b1caedf0bab1
Create Date: 2025-02-19 14:48:41.403590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14107f8df40b'
down_revision: Union[str, None] = 'b1caedf0bab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_cour', sa.Column('from_inventory_city', sa.String(), nullable=False))
    op.add_column('inventory_cour', sa.Column('to_inventory_city', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'inventory_cour', ['order_id'])
    op.drop_column('inventory_cour', 'to_inventory_id')
    op.drop_column('inventory_cour', 'from_inventory_id')
    op.add_column('inventory_del', sa.Column('inventory_city', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'inventory_del', ['order_id'])
    op.drop_column('inventory_del', 'inventory_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_del', sa.Column('inventory_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inventory_del', type_='unique')
    op.drop_column('inventory_del', 'inventory_city')
    op.add_column('inventory_cour', sa.Column('from_inventory_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('inventory_cour', sa.Column('to_inventory_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inventory_cour', type_='unique')
    op.drop_column('inventory_cour', 'to_inventory_city')
    op.drop_column('inventory_cour', 'from_inventory_city')
    # ### end Alembic commands ###
