"""empty message

Revision ID: 4493a638824f
Revises: ae91f4494c4b
Create Date: 2025-02-19 10:34:57.537715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4493a638824f'
down_revision: Union[str, None] = 'ae91f4494c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ship_city', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('ship_zip', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('bill_city', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('bill_zip', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'bill_zip')
    op.drop_column('orders', 'bill_city')
    op.drop_column('orders', 'ship_zip')
    op.drop_column('orders', 'ship_city')
    # ### end Alembic commands ###
