"""empty message

Revision ID: 48cf6103a331
Revises: 9a4b9cb39980
Create Date: 2025-02-17 12:34:13.831729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48cf6103a331'
down_revision: Union[str, None] = '9a4b9cb39980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('r_orders', sa.Column('order_quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('r_orders', 'order_quantity')
    # ### end Alembic commands ###
