"""empty message

Revision ID: 5b116927b345
Revises: 8c2df90105ad
Create Date: 2025-02-11 12:44:50.215211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b116927b345'
down_revision: Union[str, None] = '8c2df90105ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories_info', 'category_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('categories_info_category_id_seq'::regclass)"))
    op.drop_column('categories_info', 'parent_category')
    op.alter_column('subcategories_info', 'subcategory_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('subcategories_info_subcategory_id_seq'::regclass)"))
    op.alter_column('subcategories_info', 'category_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subcategories_info', 'category_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('subcategories_info', 'subcategory_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('subcategories_info_subcategory_id_seq'::regclass)"))
    op.add_column('categories_info', sa.Column('parent_category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('categories_info', 'category_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('categories_info_category_id_seq'::regclass)"))
    # ### end Alembic commands ###
