"""empty message

Revision ID: 73e5e982196a
Revises: 98cb5a09b0e5
Create Date: 2025-02-21 12:01:05.757237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e5e982196a'
down_revision: Union[str, None] = '98cb5a09b0e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_del', sa.Column('staff_id', sa.String(), nullable=True))
    op.add_column('inventory_del', sa.Column('coor_d1', sa.String(), nullable=True))
    op.add_column('inventory_del', sa.Column('coor_d2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_del', 'coor_d2')
    op.drop_column('inventory_del', 'coor_d1')
    op.drop_column('inventory_del', 'staff_id')
    # ### end Alembic commands ###
