"""empty message

Revision ID: 8c2df90105ad
Revises: f670abfaf4f4
Create Date: 2025-02-11 12:22:05.989241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c2df90105ad'
down_revision: Union[str, None] = 'f670abfaf4f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_info',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parent_category', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verify', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('subcategories_info',
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('subcategory_id')
    )
    op.drop_table('catgories_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catgories_info',
    sa.Column('catgorie_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('catorgie', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subcatorgie', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('verify', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('catgorie_id', name='catgories_info_pkey')
    )
    op.drop_table('subcategories_info')
    op.drop_table('categories_info')
    # ### end Alembic commands ###
