"""empty message

Revision ID: ad9e0ccfcfc1
Revises: d7dfd5139f6b
Create Date: 2025-02-17 12:06:05.476015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9e0ccfcfc1'
down_revision: Union[str, None] = 'd7dfd5139f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
