"""empty message

Revision ID: ae91f4494c4b
Revises: 9e9b817e7bbd
Create Date: 2025-02-18 12:59:43.309250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae91f4494c4b'
down_revision: Union[str, None] = '9e9b817e7bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers_info', sa.Column('city', sa.String()))
    op.add_column('sellers_info', sa.Column('zip_code', sa.Integer()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers_info', 'zip_code')
    op.drop_column('sellers_info', 'city')
    # ### end Alembic commands ###
