"""empty message

Revision ID: b1caedf0bab1
Revises: 2e73876e9184
Create Date: 2025-02-19 11:37:01.725890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1caedf0bab1'
down_revision: Union[str, None] = '2e73876e9184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('inventory_id', sa.String(), nullable=False),
    sa.Column('inventory_pass', sa.String(), nullable=True),
    sa.Column('inventory_city', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    op.create_table('inventory_cour',
    sa.Column('from_inventory_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('courier_id', sa.String(), nullable=False),
    sa.Column('courier_name', sa.String(), nullable=False),
    sa.Column('courier_fee', sa.String(), nullable=False),
    sa.Column('to_inventory_id', sa.String(), nullable=False),
    sa.Column('from_inventory_status', sa.String(), nullable=True),
    sa.Column('to_inventory_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('from_inventory_id', 'to_inventory_id')
    )
    op.create_table('inventory_del',
    sa.Column('inventory_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.Column('coor1', sa.String(), nullable=True),
    sa.Column('coor2', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_del')
    op.drop_table('inventory_cour')
    op.drop_table('inventory')
    # ### end Alembic commands ###
