"""empty message

Revision ID: b7fe2ad8138d
Revises: 38dd1e10aeb1
Create Date: 2025-02-11 15:12:11.892596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7fe2ad8138d'
down_revision: Union[str, None] = '38dd1e10aeb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discount', sa.String(), nullable=False))
    op.add_column('products', sa.Column('product_details', sa.String(), nullable=False))
    op.add_column('products', sa.Column('product_status', sa.String(), nullable=False))
    op.add_column('products', sa.Column('verify', sa.Boolean(), nullable=False))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('seller_work', 'seller_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('seller_work', 'order_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seller_work', 'order_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('seller_work', 'seller_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('products', 'verify')
    op.drop_column('products', 'product_status')
    op.drop_column('products', 'product_details')
    op.drop_column('products', 'discount')
    # ### end Alembic commands ###
