"""empty message

Revision ID: d3faeda54479
Revises: b7fe2ad8138d
Create Date: 2025-02-11 16:33:33.450686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3faeda54479'
down_revision: Union[str, None] = 'b7fe2ad8138d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('subcategory_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'subcategory_id')
    # ### end Alembic commands ###
