"""empty message

Revision ID: d5564fe03a2a
Revises: d3faeda54479
Create Date: 2025-02-12 04:42:45.055369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5564fe03a2a'
down_revision: Union[str, None] = 'd3faeda54479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
