"""empty message

Revision ID: d749525c3aa5
Revises: 08c521ee7bb7
Create Date: 2025-02-12 12:17:10.152746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd749525c3aa5'
down_revision: Union[str, None] = '08c521ee7bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers_info', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers_info', 'address')
    # ### end Alembic commands ###
