"""empty message

Revision ID: d7dfd5139f6b
Revises: e0e9b1b40e62
Create Date: 2025-02-17 11:27:45.917596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7dfd5139f6b'
down_revision: Union[str, None] = 'e0e9b1b40e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cart',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('products', sa.String(), nullable=True),
    sa.Column('product_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_cart')
    # ### end Alembic commands ###
