"""empty message

Revision ID: e0e9b1b40e62
Revises: 384f520105e3
Create Date: 2025-02-17 10:57:24.779961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0e9b1b40e62'
down_revision: Union[str, None] = '384f520105e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wishlist', 'products',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wishlist', 'products',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
