"""empty message

Revision ID: e760ee8096a1
Revises: ef94a71575af
Create Date: 2025-02-14 10:47:22.579446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e760ee8096a1'
down_revision: Union[str, None] = 'ef94a71575af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_a',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('users', sa.Column('user_profile', sa.String(), nullable=True))
    op.drop_column('users', 'verify')
    op.drop_column('users', 'order_id')
    op.drop_column('users', 'cart')
    op.drop_column('users', 'wishlist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wishlist', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('cart', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('verify', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'user_profile')
    op.drop_table('users_a')
    # ### end Alembic commands ###
