"""empty message

Revision ID: f16d01e7842f
Revises: 14107f8df40b
Create Date: 2025-02-19 15:36:45.573161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16d01e7842f'
down_revision: Union[str, None] = '14107f8df40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_cour',
    sa.Column('from_inventory_city', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('courier_id', sa.String(), nullable=False),
    sa.Column('courier_name', sa.String(), nullable=False),
    sa.Column('courier_fee', sa.String(), nullable=False),
    sa.Column('to_inventory_city', sa.String(), nullable=False),
    sa.Column('from_inventory_status', sa.String(), nullable=True),
    sa.Column('to_inventory_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('from_inventory_city'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('inventory_del',
    sa.Column('inventory_city', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.Column('coor1', sa.String(), nullable=True),
    sa.Column('coor2', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('inventory_city'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_del')
    op.drop_table('inventory_cour')
    # ### end Alembic commands ###
