"""empty message

Revision ID: f3e0a4d1876a
Revises: 113919548772
Create Date: 2025-02-12 12:08:57.499236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e0a4d1876a'
down_revision: Union[str, None] = '113919548772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('sellers_info', sa.Column('address', sa.String(), nullable=True))

    # Step 2: Fill existing rows with a default value
    op.execute("UPDATE sellers_info SET address = 'Unknown' WHERE address IS NULL")

    # Step 3: Alter column to NOT NULL
    op.alter_column('sellers_info', 'address', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers_info', 'address')
    # ### end Alembic commands ###
