"""empty message

Revision ID: f670abfaf4f4
Revises: 668c215c4c1f
Create Date: 2025-02-11 11:04:10.274688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f670abfaf4f4'
down_revision: Union[str, None] = '668c215c4c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sellers_info', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sellers_info', type_='unique')
    # ### end Alembic commands ###
