"""empty message

Revision ID: ff2200f90a31
Revises: b9d316cebf4d
Create Date: 2025-02-17 12:27:54.132332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2200f90a31'
down_revision: Union[str, None] = 'b9d316cebf4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('r_orders', 'return_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('r_orders', sa.Column('return_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
